[Yubikey]
# TODO: permit multiple yubico api accounts
YUBICO_CLIENT_ID = <ID>
# TODO: permit multiple yubico api accounts
YUBICO_SECRET_KEY_B64 = <SECRET KEY>
# TODO: permit multiple yubico api accounts
YUBICO_CLIENTS_DATABASE_PATH = yubikey.db
YUBICO_VERIFY_URL = https://api.yubico.com/wsapi/2.0/verify

[General]
INTERFACE = wgvpn0
# perhaps confusing to specify this in two places?
ADDRESS_POOL_V4 = 10.0.0.0/24
# select something higher than 1 to retain e.g. ".2"
RESERVED_ADDRESS_COUNT = 2
ENDPOINT = <ip>:<port>

[Watchdog]
WATCH_INTERVAL_SECONDS = 5
PEER_TIMEOUT_SECONDS = 3600
PERMIT_IP_CHANGE = no

[Server]
BIND_ADDRESS = 10.0.1.1
BIND_PORT = 80
DOWNLOAD_CACHE = yes
DOWNLOAD_TTL = 300

[Peers]
DATABASE_PATH = peers.db
CONFIGURE_PRESHARED_KEY = yes
CONFIGURE_KEEP_ALIVE = yes
KEEP_ALIVE_SECONDS = 60
ALLOWED_IPS = 10.0.0.0/24
CONFIGURE_DNS = off
DNS = 
INTERFACE_NAME = vpn

[Accounts]
DATABASE_PATH = accounts.db

[Debug]
DRY_RUN = no
